# Generated by Django 2.1.5 on 2019-01-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RwbReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_number', models.CharField(max_length=255)),
                ('date_import', models.IntegerField(default=0)),
                ('date_export', models.IntegerField(default=0)),
                ('md5hash', models.CharField(default='', max_length=32)),
                ('doc_date', models.CharField(max_length=50)),
                ('sender', models.IntegerField(default=0)),
                ('recipient', models.IntegerField(default=0)),
                ('cargo', models.IntegerField(default=0)),
                ('qty', models.IntegerField(default=0)),
                ('cargo_net', models.CharField(max_length=50)),
                ('customer', models.IntegerField(default=0)),
                ('recipient2', models.IntegerField(default=0)),
                ('station', models.IntegerField(default=0)),
                ('contract', models.CharField(max_length=50)),
                ('gtd', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
