# Generated by Django 2.1.5 on 2019-01-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adapter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RwbReceiptCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_number', models.CharField(max_length=255)),
                ('date_import', models.IntegerField(default=0)),
                ('date_export', models.IntegerField(default=0)),
                ('md5hash', models.CharField(default='', max_length=32)),
                ('rwbill_no', models.CharField(max_length=50)),
                ('car_no', models.CharField(max_length=10)),
                ('cargo_net', models.CharField(max_length=50)),
                ('contract', models.IntegerField(default=0)),
                ('gtd', models.CharField(max_length=50)),
                ('condition', models.IntegerField(default=0)),
                ('state', models.IntegerField(default=0)),
                ('contract_trade', models.IntegerField(default=0)),
                ('owner', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='rwbreceipt',
            name='contract',
            field=models.IntegerField(default=0),
        ),
    ]
