# Generated by Django 2.1.5 on 2019-01-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adapter', '0003_auto_20190128_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='RwbReceiptMemo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_number', models.CharField(max_length=255, unique=True)),
                ('date_import', models.IntegerField(default=0)),
                ('date_export', models.IntegerField(default=0)),
                ('md5hash', models.CharField(default='', max_length=32)),
                ('route', models.CharField(max_length=50)),
                ('memo', models.CharField(max_length=50)),
                ('notice', models.IntegerField(default=0)),
                ('path_no', models.IntegerField(default=0)),
                ('in_date', models.CharField(max_length=10)),
                ('in_time', models.CharField(max_length=5)),
                ('end_date', models.CharField(max_length=10)),
                ('end_time', models.CharField(max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RwbReceiptMemoCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_number', models.CharField(max_length=255, unique=True)),
                ('date_import', models.IntegerField(default=0)),
                ('date_export', models.IntegerField(default=0)),
                ('md5hash', models.CharField(default='', max_length=32)),
                ('rwbill_no', models.CharField(max_length=50)),
                ('car_no', models.CharField(max_length=10)),
                ('date_in', models.CharField(max_length=10)),
                ('time_in', models.CharField(max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
