# Generated by Django 2.1.5 on 2019-01-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adapter', '0004_rwbreceiptmemo_rwbreceiptmemocar'),
    ]

    operations = [
        migrations.AddField(
            model_name='rwbreceiptmemocar',
            name='route_memo_notice',
            field=models.CharField(default='', max_length=255),
        ),
    ]
