# Generated by Django 2.1.5 on 2019-01-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adapter', '0005_rwbreceiptmemocar_route_memo_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='RwbGtd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_number', models.CharField(max_length=255, unique=True)),
                ('date_import', models.IntegerField(default=0)),
                ('date_export', models.IntegerField(default=0)),
                ('md5hash', models.CharField(default='', max_length=32)),
                ('cargo', models.IntegerField(default=0)),
                ('cargo_net', models.CharField(max_length=50)),
                ('doc_date', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
