# Generated by Django 2.1.5 on 2019-01-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RwbReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_number', models.CharField(max_length=255)),
                ('date_import', models.IntegerField(default=0)),
                ('date_export', models.IntegerField(default=0)),
                ('route', models.CharField(max_length=50)),
                ('doc_date', models.CharField(max_length=50)),
                ('sender', models.IntegerField(default=0)),
                ('recipient', models.IntegerField(default=0)),
                ('cargo', models.IntegerField(default=0)),
                ('qty', models.IntegerField(default=0)),
                ('cargo_net', models.FloatField(default=0)),
                ('contract', models.IntegerField(default=0)),
                ('customer', models.IntegerField(default=0)),
                ('recipient2', models.IntegerField(default=0)),
                ('station', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RwbReceiptCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_import', models.IntegerField(default=0)),
                ('date_export', models.IntegerField(default=0)),
                ('key_number', models.CharField(max_length=255)),
                ('rwbill_no', models.CharField(max_length=255)),
                ('car_no', models.CharField(max_length=255)),
                ('cargo_net', models.FloatField(default=0)),
                ('contract', models.IntegerField(default=0)),
                ('gtd', models.CharField(max_length=255)),
                ('condition', models.IntegerField(default=0)),
                ('state', models.IntegerField(default=0)),
                ('contract_trade', models.IntegerField(default=0)),
                ('owner', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RwbReceiptExt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_number', models.CharField(max_length=255)),
                ('date_import', models.IntegerField(default=0)),
                ('date_export', models.IntegerField(default=0)),
                ('rwbill_no', models.CharField(max_length=255)),
                ('contract', models.IntegerField(default=0)),
                ('gtd', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
