# Generated by Django 2.1.5 on 2019-01-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rwbreceipt',
            name='cargo_net',
            field=models.CharField(max_length=50),
        ),
    ]
