# Generated by Django 2.1.5 on 2019-01-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0002_auto_20190123_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='rwbreceipt',
            name='md5hash',
            field=models.CharField(default='', max_length=32),
        ),
    ]
