# Generated by Django 2.1.5 on 2019-01-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0003_rwbreceipt_md5hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='rwbreceiptcar',
            name='md5hash',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='rwbreceiptext',
            name='md5hash',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='rwbreceiptcar',
            name='car_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='rwbreceiptcar',
            name='cargo_net',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rwbreceiptcar',
            name='gtd',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rwbreceiptcar',
            name='rwbill_no',
            field=models.CharField(max_length=50),
        ),
    ]
