# Generated by Django 2.1.5 on 2019-01-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0004_auto_20190123_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rwbreceiptext',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='rwbreceiptext',
            name='gtd',
        ),
        migrations.RemoveField(
            model_name='rwbreceiptext',
            name='rwbill_no',
        ),
        migrations.AddField(
            model_name='rwbreceiptext',
            name='gtd_contract',
            field=models.TextField(default=''),
        ),
    ]
