# Generated by Django 2.1.5 on 2019-01-25 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0008_auto_20190125_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rwbreceipt',
            name='date_export',
        ),
        migrations.RemoveField(
            model_name='rwbreceiptcar',
            name='date_export',
        ),
        migrations.RemoveField(
            model_name='rwbreceiptcartime',
            name='date_export',
        ),
        migrations.RemoveField(
            model_name='rwbreceiptnotice',
            name='date_export',
        ),
        migrations.RemoveField(
            model_name='rwbreceiptnoticetime',
            name='date_export',
        ),
    ]
